const mockDepartments = [
  { id: 1, name: 'Human Resources', locationID: 1 },
  { id: 2, name: 'Sales', locationID: 2 },
  { id: 3, name: 'Marketing', locationID: 2 },
  { id: 4, name: 'Legal', locationID: 1 },
  { id: 5, name: 'Services', locationID: 1 },
  { id: 6, name: 'Research and Development', locationID: 3 },
  { id: 7, name: 'Product Management', locationID: 3 },
  { id: 8, name: 'Training', locationID: 4 },
  { id: 9, name: 'Support', locationID: 4 },
  { id: 10, name: 'Engineering', locationID: 5 },
  { id: 11, name: 'Accounting', locationID: 5 },
  { id: 12, name: 'Business Development', locationID: 3 },
];

const mockLocations = [
  { id: 1, name: 'London' },
  { id: 2, name: 'New York' },
  { id: 3, name: 'Paris' },
  { id: 4, name: 'Munich' },
  { id: 5, name: 'Rome' },
  { id: 6, name: 'Bristol' },
  { id: 7, name: 'Warsaw' },
  { id: 8, name: 'Berlin' },
];

const mockPersonnel = [
  { id: 1, firstName: 'Robert', lastName: 'Heffron', jobTitle: '', email: 'rheffron0@ibm.com', departmentID: 1, locationID: 1 },
  { id: 2, firstName: 'Kris', lastName: 'Kovnot', jobTitle: '', email: 'kkovnot1@google.nl', departmentID: 2, locationID: 2 },
  { id: 3, firstName: 'Vera', lastName: 'Kisbee', jobTitle: '', email: 'vkisbee2@nih.gov', departmentID: 2, locationID: 8 },
  { id: 4, firstName: 'Aveline', lastName: 'Edgson', jobTitle: '', email: 'aedgson3@wikispaces.com', departmentID: 3, locationID: 2 },
  { id: 5, firstName: 'Bertie', lastName: 'Wittke', jobTitle: '', email: 'bwittke4@yahoo.com', departmentID: 4, locationID: 1 },
  { id: 6, firstName: 'Demetre', lastName: 'Cossam', jobTitle: '', email: 'dcossam5@washington.edu', departmentID: 5, locationID: 1 },
  { id: 7, firstName: 'Annabela', lastName: 'McGavigan', jobTitle: '', email: 'amcgavigan6@wp.com', departmentID: 4, locationID: 7 },
  { id: 8, firstName: 'Crichton', lastName: 'McAndrew', jobTitle: '', email: 'cmcandrew7@zdnet.com', departmentID: 1, locationID: 6 },
  { id: 9, firstName: 'Cordula', lastName: 'Plain', jobTitle: '', email: 'cplain8@google.ca', departmentID: 5, locationID: 1 },
  { id: 10, firstName: 'Glen', lastName: 'McDougle', jobTitle: '', email: 'gmcdougle9@meetup.com', departmentID: 6, locationID: 3 },
  { id: 11, firstName: 'Theo', lastName: 'Audas', jobTitle: '', email: 'taudasa@newsvine.com', departmentID: 7, locationID: 3 },
  { id: 12, firstName: 'Spense', lastName: 'Jolliss', jobTitle: '', email: 'sjollissb@wufoo.com', departmentID: 8, locationID: 4 },
  { id: 13, firstName: 'Leopold', lastName: 'Carl', jobTitle: '', email: 'lcarlc@paginegialle.it', departmentID: 9, locationID: 4 },
  { id: 14, firstName: 'Barr', lastName: 'MacAllan', jobTitle: '', email: 'bmacalland@github.com', departmentID: 5, locationID: 1 },
  { id: 15, firstName: 'Suzie', lastName: 'Cromer', jobTitle: '', email: 'scromere@imageshack.us', departmentID: 1, locationID: 8 },
  { id: 16, firstName: 'Tracee', lastName: 'Gisbourn', jobTitle: '', email: 'tgisbournf@bloglines.com', departmentID: 10, locationID: 5 },
  { id: 17, firstName: 'Taylor', lastName: 'St. Quintin', jobTitle: '', email: 'tstquinting@chronoengine.com', departmentID: 10, locationID: 5 },
  { id: 18, firstName: 'Lin', lastName: 'Klassmann', jobTitle: '', email: 'lklassmannh@indiatimes.com', departmentID: 10, locationID: 5 },
  { id: 19, firstName: 'Lay', lastName: 'Fintoph', jobTitle: '', email: 'lfintophi@goo.gl', departmentID: 11, locationID: 5 },
  { id: 20, firstName: 'Moishe', lastName: 'Flinn', jobTitle: '', email: 'mflinnj@list-manage.com', departmentID: 12, locationID: 3 },
  { id: 21, firstName: 'Gay', lastName: 'Bickford', jobTitle: '', email: 'gbickfordk@scientificamerican.com', departmentID: 6, locationID: 3 },
  { id: 22, firstName: 'Erik', lastName: 'Lindback', jobTitle: '', email: 'elindbackl@virginia.edu', departmentID: 8, locationID: 4 },
  { id: 23, firstName: 'Tamarra', lastName: 'Ace', jobTitle: '', email: 'tacem@vinaora.com', departmentID: 9, locationID: 4 },
  { id: 24, firstName: 'Barbara-anne', lastName: 'Rooksby', jobTitle: '', email: 'brooksbyn@issuu.com', departmentID: 12, locationID: 3 },
  { id: 25, firstName: 'Lucien', lastName: 'Allsup', jobTitle: '', email: 'lallsupo@goo.ne.jp', departmentID: 9, locationID: 4 },
  { id: 26, firstName: 'Jackelyn', lastName: 'Imlach', jobTitle: '', email: 'jimlachp@google.it', departmentID: 11, locationID: 5 },
  { id: 27, firstName: 'Virge', lastName: 'Bootes', jobTitle: '', email: 'vbootesq@oracle.com', departmentID: 2, locationID: 2 },
  { id: 28, firstName: 'Rafferty', lastName: 'Matasov', jobTitle: '', email: 'rmatasovr@4shared.com', departmentID: 4, locationID: 1 },
  { id: 29, firstName: 'Vanya', lastName: 'Goulder', jobTitle: '', email: 'vgoulders@phoca.cz', departmentID: 9, locationID: 4 },
  { id: 30, firstName: 'Bonita', lastName: 'McGonagle', jobTitle: '', email: 'bmcgonaglet@microsoft.com', departmentID: 1, locationID: 8 },
  { id: 31, firstName: 'Allx', lastName: 'Whaley', jobTitle: '', email: 'awhaleyu@bbb.org', departmentID: 1, locationID: 1 },
  { id: 32, firstName: 'Mavis', lastName: 'Lernihan', jobTitle: '', email: 'mlernihanv@netscape.com', departmentID: 5, locationID: 8 },
  { id: 33, firstName: 'Vern', lastName: 'Durling', jobTitle: '', email: 'vdurlingw@goo.gl', departmentID: 1, locationID: 1 },
  { id: 34, firstName: 'Myles', lastName: 'Minchi', jobTitle: '', email: 'mminchix@smugmug.com', departmentID: 7, locationID: 3 },
  { id: 35, firstName: 'Anitra', lastName: 'Coleridge', jobTitle: '', email: 'acoleridgey@nbcnews.com', departmentID: 6, locationID: 3 },
  { id: 36, firstName: 'Ailis', lastName: 'Brewster', jobTitle: '', email: 'abrewsterz@businesswire.com', departmentID: 7, locationID: 3 },
  { id: 37, firstName: 'Rahal', lastName: 'Tute', jobTitle: '', email: 'rtute10@pinterest.com', departmentID: 6, locationID: 3 },
  { id: 38, firstName: 'Warner', lastName: 'Blonden', jobTitle: '', email: 'wblonden11@spiegel.de', departmentID: 12, locationID: 3 },
  { id: 39, firstName: 'Melvyn', lastName: 'Canner', jobTitle: '', email: 'mcanner12@eepurl.com', departmentID: 4, locationID: 1 },
  { id: 40, firstName: 'Ryann', lastName: 'Giampietro', jobTitle: '', email: 'rgiampietro13@theguardian.com', departmentID: 4, locationID: 1 },
  { id: 41, firstName: 'Harwell', lastName: 'Jefferys', jobTitle: '', email: 'hjefferys14@jimdo.com', departmentID: 10, locationID: 5 },
  { id: 42, firstName: 'Lanette', lastName: 'Buss', jobTitle: '', email: 'lbuss15@51.la', departmentID: 4, locationID: 1 },
  { id: 43, firstName: 'Lissie', lastName: 'Reddington', jobTitle: '', email: 'lreddington16@w3.org', departmentID: 9, locationID: 4 },
  { id: 44, firstName: 'Dore', lastName: 'Braidford', jobTitle: '', email: 'dbraidford17@google.com.br', departmentID: 11, locationID: 7 },
  { id: 45, firstName: 'Lizabeth', lastName: 'Di Franceshci', jobTitle: '', email: 'ldifranceshci18@mediafire.com', departmentID: 8, locationID: 4 },
  { id: 46, firstName: 'Felic', lastName: 'Sharland', jobTitle: '', email: 'fsharland19@myspace.com', departmentID: 12, locationID: 3 },
  { id: 47, firstName: 'Duff', lastName: 'Quail', jobTitle: '', email: 'dquail1a@vimeo.com', departmentID: 9, locationID: 4 },
  { id: 48, firstName: 'Brendis', lastName: 'Shivell', jobTitle: '', email: 'bshivell1b@un.org', departmentID: 1, locationID: 1 },
  { id: 49, firstName: 'Nevile', lastName: 'Schimaschke', jobTitle: '', email: 'nschimaschke1c@hexun.com', departmentID: 10, locationID: 5 },
  { id: 50, firstName: 'Jon', lastName: 'Calbaithe', jobTitle: '', email: 'jcalbaithe1d@netvibes.com', departmentID: 4, locationID: 1 },
  { id: 51, firstName: 'Emmery', lastName: 'Darben', jobTitle: '', email: 'edarben1e@mapquest.com', departmentID: 10, locationID: 5 },
  { id: 52, firstName: 'Staford', lastName: 'Whitesel', jobTitle: '', email: 'swhitesel1f@nasa.gov', departmentID: 6, locationID: 8 },
  { id: 53, firstName: 'Benjamin', lastName: 'Hawkslee', jobTitle: '', email: 'bhawkslee1g@hubpages.com', departmentID: 7, locationID: 3 },
  { id: 54, firstName: 'Myrle', lastName: 'Speer', jobTitle: '', email: 'mspeer1h@tripod.com', departmentID: 3, locationID: 2 },
  { id: 55, firstName: 'Matthus', lastName: 'Banfield', jobTitle: '', email: 'mbanfield1i@angelfire.com', departmentID: 3, locationID: 2 },
  { id: 56, firstName: 'Annadiana', lastName: 'Drance', jobTitle: '', email: 'adrance1j@omniture.com', departmentID: 3, locationID: 2 },
  { id: 57, firstName: 'Rinaldo', lastName: 'Fandrey', jobTitle: '', email: 'rfandrey1k@bbc.co.uk', departmentID: 2, locationID: 2 },
  { id: 58, firstName: 'Roanna', lastName: 'Standering', jobTitle: '', email: 'rstandering1l@cocolog-nifty.com', departmentID: 3, locationID: 2 },
  { id: 59, firstName: 'Lorrie', lastName: 'Fattorini', jobTitle: '', email: 'lfattorini1m@geocities.jp', departmentID: 9, locationID: 4 },
  { id: 60, firstName: 'Talbot', lastName: 'Andrassy', jobTitle: '', email: 'tandrassy1n@bigcartel.com', departmentID: 4, locationID: 6 },
  { id: 61, firstName: 'Cindi', lastName: 'O\'Mannion', jobTitle: '', email: 'comannion1o@ameblo.jp', departmentID: 11, locationID: 5 },
  { id: 62, firstName: 'Pancho', lastName: 'Mullineux', jobTitle: '', email: 'pmullineux1p@webmd.com', departmentID: 1, locationID: 1 },
  { id: 63, firstName: 'Cynthy', lastName: 'Peyntue', jobTitle: '', email: 'cpeyntue1q@amazon.co.jp', departmentID: 6, locationID: 3 },
  { id: 64, firstName: 'Kristine', lastName: 'Christal', jobTitle: '', email: 'kchristal1r@behance.net', departmentID: 8, locationID: 4 },
  { id: 65, firstName: 'Dniren', lastName: 'Reboulet', jobTitle: '', email: 'dreboulet1s@360.cn', departmentID: 7, locationID: 3 },
  { id: 66, firstName: 'Aggy', lastName: 'Napier', jobTitle: '', email: 'anapier1t@sciencedirect.com', departmentID: 3, locationID: 2 },
  { id: 67, firstName: 'Gayleen', lastName: 'Hessay', jobTitle: '', email: 'ghessay1u@exblog.jp', departmentID: 4, locationID: 1 },
  { id: 68, firstName: 'Cull', lastName: 'Snoden', jobTitle: '', email: 'csnoden1v@so-net.ne.jp', departmentID: 1, locationID: 1 },
  { id: 69, firstName: 'Vlad', lastName: 'Crocombe', jobTitle: '', email: 'vcrocombe1w@mtv.com', departmentID: 7, locationID: 3 },
  { id: 70, firstName: 'Georgeanna', lastName: 'Joisce', jobTitle: '', email: 'gjoisce1x@google.com.au', departmentID: 6, locationID: 3 },
  { id: 71, firstName: 'Ursola', lastName: 'Berthomieu', jobTitle: '', email: 'uberthomieu1y@un.org', departmentID: 4, locationID: 1 },
  { id: 72, firstName: 'Mair', lastName: 'McKirdy', jobTitle: '', email: 'mmckirdy1z@ovh.net', departmentID: 1, locationID: 1 },
  { id: 73, firstName: 'Erma', lastName: 'Runnalls', jobTitle: '', email: 'erunnalls20@spiegel.de', departmentID: 8, locationID: 4 },
  { id: 74, firstName: 'Heida', lastName: 'Gallone', jobTitle: '', email: 'hgallone21@hostgator.com', departmentID: 10, locationID: 8 },
  { id: 75, firstName: 'Christina', lastName: 'Denge', jobTitle: '', email: 'cdenge22@canalblog.com', departmentID: 12, locationID: 3 },
  { id: 76, firstName: 'Wilone', lastName: 'Fredi', jobTitle: '', email: 'wfredi23@gizmodo.com', departmentID: 7, locationID: 3 },
  { id: 77, firstName: 'Stormie', lastName: 'Bolderstone', jobTitle: '', email: 'sbolderstone24@globo.com', departmentID: 11, locationID: 5 },
  { id: 78, firstName: 'Darryl', lastName: 'Pool', jobTitle: '', email: 'dpool25@vistaprint.com', departmentID: 11, locationID: 5 },
  { id: 79, firstName: 'Nikolas', lastName: 'Mager', jobTitle: '', email: 'nmager26@nifty.com', departmentID: 5, locationID: 1 },
  { id: 80, firstName: 'Brittney', lastName: 'Gaskal', jobTitle: '', email: 'bgaskal27@weather.com', departmentID: 10, locationID: 5 },
  { id: 81, firstName: 'Field', lastName: 'Gresty', jobTitle: '', email: 'fgresty28@networkadvertising.org', departmentID: 4, locationID: 1 },
  { id: 82, firstName: 'Martina', lastName: 'Tremoulet', jobTitle: '', email: 'mtremoulet29@sciencedaily.com', departmentID: 3, locationID: 8 },
  { id: 83, firstName: 'Robena', lastName: 'Ivanyutin', jobTitle: '', email: 'rivanyutin2a@mozilla.org', departmentID: 2, locationID: 2 },
  { id: 84, firstName: 'Reagen', lastName: 'Corner', jobTitle: '', email: 'rcorner2b@qq.com', departmentID: 11, locationID: 5 },
  { id: 85, firstName: 'Eveleen', lastName: 'Sulter', jobTitle: '', email: 'esulter2c@nature.com', departmentID: 6, locationID: 3 },
  { id: 86, firstName: 'Christy', lastName: 'Dunbobbin', jobTitle: '', email: 'cdunbobbin2d@feedburner.com', departmentID: 8, locationID: 6 },
  { id: 87, firstName: 'Winthrop', lastName: 'Lansley', jobTitle: '', email: 'wlansley2e@alibaba.com', departmentID: 8, locationID: 4 },
  { id: 88, firstName: 'Lissa', lastName: 'Insley', jobTitle: '', email: 'linsley2f@friendfeed.com', departmentID: 3, locationID: 2 },
  { id: 89, firstName: 'Shell', lastName: 'Risebarer', jobTitle: '', email: 'srisebarer2g@patch.com', departmentID: 10, locationID: 5 },
  { id: 90, firstName: 'Cherianne', lastName: 'Liddyard', jobTitle: '', email: 'cliddyard2h@com.com', departmentID: 2, locationID: 2 },
  { id: 91, firstName: 'Brendan', lastName: 'Fooks', jobTitle: '', email: 'bfooks2i@utexas.edu', departmentID: 2, locationID: 2 },
  { id: 92, firstName: 'Edmund', lastName: 'Tace', jobTitle: '', email: 'etace2j@hatena.ne.jp', departmentID: 9, locationID: 4 },
  { id: 93, firstName: 'Ki', lastName: 'Tomasini', jobTitle: '', email: 'ktomasini2k@cnbc.com', departmentID: 10, locationID: 5 },
  { id: 94, firstName: 'Chadd', lastName: 'McGettrick', jobTitle: '', email: 'cmcgettrick2l@simplemachines.org', departmentID: 10, locationID: 5 },
  { id: 95, firstName: 'Dulcie', lastName: 'Baudi', jobTitle: '', email: 'dbaudi2m@last.fm', departmentID: 3, locationID: 2 },
  { id: 96, firstName: 'Barnebas', lastName: 'Mowbray', jobTitle: '', email: 'bmowbray2n@cbslocal.com', departmentID: 1, locationID: 1 },
  { id: 97, firstName: 'Stefanie', lastName: 'Anker', jobTitle: '', email: 'sanker2o@hud.gov', departmentID: 5, locationID: 1 },
  { id: 98, firstName: 'Cherye', lastName: 'de Cullip', jobTitle: '', email: 'cdecullip2p@loc.gov', departmentID: 10, locationID: 8 },
  { id: 99, firstName: 'Sinclare', lastName: 'Deverall', jobTitle: '', email: 'sdeverall2q@ow.ly', departmentID: 6, locationID: 3 },
  { id: 100, firstName: 'Shae', lastName: 'Johncey', jobTitle: '', email: 'sjohncey2r@bluehost.com', departmentID: 10, locationID: 7 }
];